- name: Create new EC2 instance
  hosts: localhost
  connection: local
  
  tasks:
    - name: Launch EC2 instance
      ec2: 
        instance_type: t2.micro
        image: ami-0c02fb55956c7d316
        region: us-east-1
        key_name: devops-ansible
        vpc_subnet_id: subnet-0317d6be2b88cd277
        assign_public_ip: yes
        wait: yes
        count: 1
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}"